// TRENDING_ALL_CATEGORIES_LIST
export const TRENDING_ALL_CATEGORIES_LIST_REQUEST =
  "TRENDING_ALL_CATEGORIES_LIST_REQUEST";
export const TRENDING_ALL_CATEGORIES_LIST_SUCCESS =
  "TRENDING_ALL_CATEGORIES_LIST_SUCCESS";
export const TRENDING_ALL_CATEGORIES_LIST_RESET =
  "TRENDING_ALL_CATEGORIES_LIST_RESET";
export const TRENDING_ALL_CATEGORIES_LIST_FAILURE =
  "TRENDING_ALL_CATEGORIES_LIST_FAILURE";

// SEARCH_TRADIE_SERVICE
export const SEARCH_TRADIE_SERVICE_REQUEST = "SEARCH_TRADIE_SERVICE_REQUEST";
export const SEARCH_TRADIE_SERVICE_SUCCESS = "SEARCH_TRADIE_SERVICE_SUCCESS";
export const SEARCH_TRADIE_SERVICE_RESET = "SEARCH_TRADIE_SERVICE_RESET";
export const SEARCH_TRADIE_SERVICE_FAILURE = "SEARCH_TRADIE_SERVICE_FAILURE";

// SEARCH_TRADIE_SERVICE
export const SEARCH_TRADIE_SERVICE_CLICK_REQUEST =
  "SEARCH_TRADIE_SERVICE_CLICK_REQUEST";
export const SEARCH_TRADIE_SERVICE_CLICK_SUCCESS =
  "SEARCH_TRADIE_SERVICE_CLICK_SUCCESS";
export const SEARCH_TRADIE_SERVICE_CLICK_RESET =
  "SEARCH_TRADIE_SERVICE_CLICK_RESET";
export const SEARCH_TRADIE_SERVICE__CLICK_FAILURE =
  "SEARCH_TRADIE_SERVICE__CLICK_FAILURE";

//selected tradie id
export const SELECTED_TRADIE_PROFILE_ID_REQUEST =
  "SELECTED_TRADIE_PROFILE_ID_REQUEST";

//selected tradie id
export const SELECTED__TO_ALL_TRADIE_PROFILE_ID_REQUEST =
  "SELECTED__TO_ALL_TRADIE_PROFILE_ID_REQUEST";

// USER_JOB_REQUEST_TO_TRADIE
export const USER_JOB_REQUEST_TO_TRADIE_REQUEST =
  "USER_JOB_REQUEST_TO_TRADIE_REQUEST";
export const USER_JOB_REQUEST_TO_TRADIE_SUCCESS =
  "USER_JOB_REQUEST_TO_TRADIE_SUCCESS";
export const USER_JOB_REQUEST_TO_TRADIE_RESET =
  "USER_JOB_REQUEST_TO_TRADIE_RESET";
export const USER_JOB_REQUEST_TO_TRADIE_FAILURE =
  "USER_JOB_REQUEST_TO_TRADIE_FAILURE";

// USER_TRADIE
export const USER_LEADS_REQUEST = "USER_LEADS_REQUEST";
export const USER_LEADS_SUCCESS = "USER_LEADS_SUCCESS";
export const USER_LEADS_RESET = "USER_LEADS_RESET";
export const USER_LEADS_FAILURE = "USER_LEADS_FAILURE";

// USER_TRADIE_HISTORY
export const USER_LEADS_HISTORY_REQUEST = "USER_LEADS_HISTORY_REQUEST";
export const USER_LEADS_HISTORY_SUCCESS = "USER_LEADS_HISTORY_SUCCESS";
export const USER_LEADS_HISTORY_RESET = "USER_LEADS_HISTORY_RESET";
export const USER_LEADS_HISTORY_FAILURE = "USER_LEADS_HISTORY_FAILURE";

// SINGLE_TRADIE_DELETE
export const USER_SINGLE_LEAD_REQUEST = "USER_SINGLE_LEAD_REQUEST";
export const USER_SINGLE_LEAD_SUCCESS = "USER_SINGLE_LEAD_SUCCESS";
export const USER_SINGLE_LEAD_RESET = "USER_SINGLE_LEAD_RESET";
export const USER_SINGLE_LEAD_FAILURE = "USER_SINGLE_LEAD_FAILURE";

// SINGLE_TRADIE_DELETE
export const SINGLE_TRADIE_DELETE_REQUEST = "SINGLE_TRADIE_DELETE_REQUEST";
export const SINGLE_TRADIE_DELETE_SUCCESS = "SINGLE_TRADIE_DELETE_SUCCESS";
export const SINGLE_TRADIE_DELETE_RESET = "SINGLE_TRADIE_DELETE_RESET";
export const SINGLE_TRADIE_DELETE_FAILURE = "SINGLE_TRADIE_DELETE_FAILURE";

// USER_JOB_DELETE
export const USER_JOB_DELETE_REQUEST = "USER_JOB_DELETE_REQUEST";
export const USER_JOB_DELETE_SUCCESS = "USER_JOB_DELETE_SUCCESS";
export const USER_JOB_DELETE_RESET = "USER_JOB_DELETE_RESET";
export const USER_JOB_DELETE_FAILURE = "USER_JOB_DELETE_FAILURE";
// USER GIVE REVIEW
export const USER_GIVE_REVIEW_ACTION = "USER_GIVE_REVIEW_ACTION";
export const USER_GIVE_REVIEW_SUCCESS = "USER_GIVE_REVIEW_SUCCESS";
export const USER_GIVE_REVIEW_RESET = "USER_GIVE_REVIEW_RESET";
export const USER_GIVE_REVIEW_FAILURE = "USER_GIVE_REVIEW_FAILURE";

export const USER_RAISE_DISPUTE_ACTION = "USER_RAISE_DISPUTE_ACTION";
export const USER_RAISE_DISPUTE_SUCCESS = "USER_RAISE_DISPUTE_SUCCESS";
export const USER_RAISE_DISPUTE_RESET = "USER_RAISE_DISPUTE_RESET";
export const USER_RAISE_DISPUTE_FAILURE = "USER_RAISE_DISPUTE_FAILURE";

// GET_PROVIDER_PROFILE
export const GET_PROVIDER_PROFILE_REQUEST = "GET_PROVIDER_PROFILE_REQUEST";
export const GET_PROVIDER_PROFILE_SUCCESS = "GET_PROVIDER_PROFILE_SUCCESS";
export const GET_PROVIDER_PROFILE_RESET = "GET_PROVIDER_PROFILE_RESET";
export const GET_PROVIDER_PROFILE_FAILURE = "GET_PROVIDER_PROFILE_FAILURE";

// GET_PROVIDER_REVIEW_LIST
export const GET_PROVIDER_REVIEW_LIST_REQUEST =
  "GET_PROVIDER_REVIEW_LIST_REQUEST";
export const GET_PROVIDER_REVIEW_LIST_SUCCESS =
  "GET_PROVIDER_REVIEW_LIST_SUCCESS";
export const GET_PROVIDER_REVIEW_LIST_RESET = "GET_PROVIDER_REVIEW_LIST_RESET";
export const GET_PROVIDER_REVIEW_LIST_FAILURE =
  "GET_PROVIDER_REVIEW_LIST_FAILURE";

// SEND_NEWS_LETTER
export const SEND_NEWS_LETTER_REQUEST = "SEND_NEWS_LETTER_REQUEST";
export const SEND_NEWS_LETTER_SUCCESS = "SEND_NEWS_LETTER_SUCCESS";
export const SEND_NEWS_LETTER_RESET = "SEND_NEWS_LETTER_LIST_RESET";
export const SEND_NEWS_LETTER_FAILURE = "SEND_NEWS_LETTER_FAILURE";

// SEND_CONTACT_FORM
export const SEND_CONTACT_FORM_REQUEST = "SEND_CONTACT_FORM_REQUEST";
export const SEND_CONTACT_FORM_SUCCESS = "SEND_CONTACT_FORM_SUCCESS";
export const SEND_CONTACT_FORM_RESET = "SEND_CONTACT_FORM_RESET";
export const SEND_CONTACT_FORM_FAILURE = "SEND_CONTACT_FORM_FAILURE";

// PROVIDER_LEADS
export const PROVIDER_LEADS_REQUEST = "PROVIDER_LEADS_REQUEST";
export const PROVIDER_LEADS_SUCCESS = "PROVIDER_LEADS_SUCCESS";
export const PROVIDER_LEADS_RESET = "PROVIDER_LEADS_RESET";
export const PROVIDER_LEADS_FAILURE = "PROVIDER_LEADS_FAILURE";

// PROVIDER_LEADS_HISTORY
export const PROVIDER_LEADS_HISTORY_REQUEST = "PROVIDER_LEADS_HISTORY_REQUEST";
export const PROVIDER_LEADS_HISTORY_SUCCESS = "PROVIDER_LEADS_HISTORY_SUCCESS";
export const PROVIDER_LEADS_HISTORY_RESET = "PROVIDER_LEADS_HISTORY_RESET";
export const PROVIDER_LEADS_HISTORY_FAILURE = "PROVIDER_LEADS_HISTORY_FAILURE";

// PROVIDER_JOB_ACCEPT
export const PROVIDER_JOB_ACCEPT_REQUEST = "PROVIDER_JOB_ACCEPT_REQUEST";
export const PROVIDER_JOB_ACCEPT_SUCCESS = "PROVIDER_JOB_ACCEPT_SUCCESS";
export const PROVIDER_JOB_ACCEPT_RESET = "PROVIDER_JOB_ACCEPT_RESET";
export const PROVIDER_JOB_ACCEPT_FAILURE = "PROVIDER_JOB_ACCEPT_FAILURE";

// PROVIDER_JOB_REJECT
export const PROVIDER_JOB_REJECT_REQUEST = "PROVIDER_JOB_REJECT_REQUEST";
export const PROVIDER_JOB_REJECT_SUCCESS = "PROVIDER_JOB_REJECT_SUCCESS";
export const PROVIDER_JOB_REJECT_RESET = "PROVIDER_JOB_REJECT_RESET";
export const PROVIDER_JOB_REJECT_FAILURE = "PROVIDER_JOB_REJECT_FAILURE";

// TRADIE_SUBSCRIPTION_LIST
export const TRADIE_SUBSCRIPTION_LIST_REQUEST =
  "TRADIE_SUBSCRIPTION_LIST_REQUEST";
export const TRADIE_SUBSCRIPTION_LIST_SUCCESS =
  "TRADIE_SUBSCRIPTION_LIST_SUCCESS";
export const TRADIE_SUBSCRIPTION_LIST_RESET = "TRADIE_SUBSCRIPTION_LIST_RESET";
export const TRADIE_SUBSCRIPTION_LIST_FAILURE =
  "TRADIE_SUBSCRIPTION_LIST_FAILURE";

// TRADIE_PAYMENT_HISTORY
export const TRADIE_PAYMENT_HISTORY_REQUEST = "TRADIE_PAYMENT_HISTORY_REQUEST";
export const TRADIE_PAYMENT_HISTORY_SUCCESS = "TRADIE_PAYMENT_HISTORY_SUCCESS";
export const TRADIE_PAYMENT_HISTORY_RESET = "TRADIE_PAYMENT_HISTORY_RESET";
export const TRADIE_PAYMENT_HISTORY_FAILURE = "TRADIE_PAYMENT_HISTORY_FAILURE";

// TRADIE_CANCEL_SUBSCRIPTION
export const TRADIE_CANCEL_SUBSCRIPTION_REQUEST =
  "TRADIE_CANCEL_SUBSCRIPTION_REQUEST";
export const TRADIE_CANCEL_SUBSCRIPTION_SUCCESS =
  "TRADIE_CANCEL_SUBSCRIPTION_SUCCESS";
export const TRADIE_CANCEL_SUBSCRIPTION_RESET =
  "TRADIE_CANCEL_SUBSCRIPTION_RESET";
export const TRADIE_CANCEL_SUBSCRIPTION_FAILURE =
  "TRADIE_CANCEL_SUBSCRIPTION_FAILURE";
