export const countryListAlpha3 = [
	{ AFG: 'Afghanistan', label: 'Afghanistan' },
	{ ALB: 'Albania', label: 'Albania' },
	{ DZA: 'Algeria', label: 'Algeria' },
	{ ASM: 'American Samoa', label: 'American Samoa' },
	{ AND: 'Andorra', label: 'Andorra' },
	{ AGO: 'Angola', label: 'Angola' },
	{ AIA: 'Anguilla', label: 'Anguilla' },
	{ ATA: 'Antarctica', label: 'Antarctica' },
	{ ATG: 'Antigua and Barbuda', label: 'Antigua and Barbuda' },
	{ ARG: 'Argentina', label: 'Argentina' },
	{ ARM: 'Armenia', label: 'Armenia' },
	{ ABW: 'Aruba', label: 'Aruba' },
	{ AUS: 'Australia', label: 'Australia' },
	{ AUT: 'Austria', label: 'Austria' },
	{ AZE: 'Azerbaijan', label: 'Azerbaijan' },
	{ BHS: 'Bahamas (the)', label: 'Bahamas (the)' },
	{ BHR: 'Bahrain', label: 'Bahrain' },
	{ BGD: 'Bangladesh', label: 'Bangladesh' },
	{ BRB: 'Barbados', label: 'Barbados' },
	{ BLR: 'Belarus', label: 'Belarus' },
	{ BEL: 'Belgium', label: 'Belgium' },
	{ BLZ: 'Belize', label: 'Belize' },
	{ BEN: 'Benin', label: 'Benin' },
	{ BMU: 'Bermuda', label: 'Bermuda' },
	{ BTN: 'Bhutan', label: 'Bhutan' },
	{ BOL: 'Bolivia (Plurinational State of)', label: 'Bolivia (Plurinational State of)' },
	{ BES: 'Bonaire Sint Eustatius and Saba', label: 'Bonaire Sint Eustatius and Saba' },
	{ BIH: 'Bosnia and Herzegovina', label: 'Bosnia and Herzegovina' },
	{ BWA: 'Botswana', label: 'Botswana' },
	{ BVT: 'Bouvet Island', label: 'Bouvet Island' },
	{ BRA: 'Brazil', label: 'Brazil' },
	{ IOT: 'British Indian Ocean Territory (the)', label: 'British Indian Ocean Territory (the)' },
	{ BRN: 'Brunei Darussalam', label: 'Brunei Darussalam' },
	{ BGR: 'Bulgaria', label: 'Bulgaria' },
	{ BFA: 'Burkina Faso', label: 'Burkina Faso' },
	{ BDI: 'Burundi', label: 'Burundi' },
	{ CPV: 'Cabo Verde', label: 'Cabo Verde' },
	{ KHM: 'Cambodia', label: 'Cambodia' },
	{ CMR: 'Cameroon', label: 'Cameroon' },
	{ CAN: 'Canada', label: 'Canada' },
	{ CYM: 'Cayman Islands (the)', label: 'Cayman Islands (the)' },
	{ CAF: 'Central African Republic (the)', label: 'Central African Republic (the)' },
	{ TCD: 'Chad', label: 'Chad' },
	{ CHL: 'Chile', label: 'Chile' },
	{ CHN: 'China', label: 'China' },
	{ CXR: 'Christmas Island', label: 'Christmas Island' },
	{ CCK: 'Cocos (Keeling) Islands (the)', label: 'Cocos (Keeling) Islands (the)' },
	{ COL: 'Colombia', label: 'Colombia' },
	{ COM: 'Comoros (the)', label: 'Comoros (the)' },
	{ COD: 'Congo (the Democratic Republic of the)', label: 'Congo (the Democratic Republic of the)' },
	{ COG: 'Congo (the)', label: 'Congo (the)' },
	{ COK: 'Cook Islands (the)', label: 'Cook Islands (the)' },
	{ CRI: 'Costa Rica', label: 'Costa Rica' },
	{ HRV: 'Croatia', label: 'Croatia' },
	{ CUB: 'Cuba', label: 'Cuba' },
	{ CUW: 'Curaçao', label: 'Curaçao' },
	{ CYP: 'Cyprus', label: 'Cyprus' },
	{ CZE: 'Czechia', label: 'Czechia' },
	{ CIV: 'Côte d Ivoire', label: 'Côte dIvoire' },
	{ DNK: 'Denmark', label: 'Denmark' },
	{ DJI: 'Djibouti', label: 'Djibouti' },
	{ DMA: 'Dominica', label: 'Dominica' },
	{ DOM: 'Dominican Republic (the)', label: 'Dominican Republic (the)' },
	{ ECU: 'Ecuador', label: 'Ecuador' },
	{ EGY: 'Egypt', label: 'Egypt' },
	{ SLV: 'El Salvador', label: 'El Salvador' },
	{ GNQ: 'Equatorial Guinea', label: 'Equatorial Guinea' },
	{ ERI: 'Eritrea', label: 'Eritrea' },
	{ EST: 'Estonia', label: 'Estonia' },
	{ SWZ: 'Eswatini', label: 'Eswatini' },
	{ ETH: 'Ethiopia', label: 'Ethiopia' },
	{ FLK: 'Falkland Islands (the) [Malvinas]', label: 'Falkland Islands (the) [Malvinas]' },
	{ FRO: 'Faroe Islands (the)', label: 'Faroe Islands (the)' },
	{ FJI: 'Fiji', label: 'Fiji' },
	{ FIN: 'Finland', label: 'Finland' },
	{ FRA: 'France', label: 'France' },
	{ GUF: 'French Guiana', label: 'French Guiana' },
	{ PYF: 'French Polynesia', label: 'French Polynesia' },
	{ ATF: 'French Southern Territories (the)', label: 'French Southern Territories (the)' },
	{ GAB: 'Gabon', label: 'Gabon' },
	{ GMB: 'Gambia (the)', label: 'Gambia (the)' },
	{ GEO: 'Georgia', label: 'Georgia' },
	{ DEU: 'Germany', label: 'Germany' },
	{ GHA: 'Ghana', label: 'Ghana' },
	{ GIB: 'Gibraltar', label: 'Gibraltar' },
	{ GRC: 'Greece', label: 'Greece' },
	{ GRL: 'Greenland', label: 'Greenland' },
	{ GRD: 'Grenada', label: 'Grenada' },
	{ GLP: 'Guadeloupe', label: 'Guadeloupe' },
	{ GUM: 'Guam', label: 'Guam' },
	{ GTM: 'Guatemala', label: 'Guatemala' },
	{ GGY: 'Guernsey', label: 'Guernsey' },
	{ GIN: 'Guinea', label: 'Guinea' },
	{ GNB: 'Guinea-Bissau', label: 'Guinea-Bissau' },
	{ GUY: 'Guyana', label: 'Guyana' },
	{ HTI: 'Haiti', label: 'Haiti' },
	{ HMD: 'Heard Island and McDonald Islands', label: 'Heard Island and McDonald Islands' },
	{ VAT: 'Holy See (the)', label: 'Holy See (the)' },
	{ HND: 'Honduras', label: 'Honduras' },
	{ HKG: 'Hong Kong', label: 'Hong Kong' },
	{ HUN: 'Hungary', label: 'Hungary' },
	{ ISL: 'Iceland', label: 'Iceland' },
	{ IND: 'India', label: 'India' },
	{ IDN: 'Indonesia', label: 'Indonesia' },
	{ IRN: 'Iran (Islamic Republic of)', label: 'Iran (Islamic Republic of)' },
	{ IRQ: 'Iraq', label: 'Iraq' },
	{ IRL: 'Ireland', label: 'Ireland' },
	{ IMN: 'Isle of Man', label: 'Isle of Man' },
	{ ISR: 'Israel', label: 'Israel' },
	{ ITA: 'Italy', label: 'Italy' },
	{ JAM: 'Jamaica', label: 'Jamaica' },
	{ JPN: 'Japan', label: 'Japan' },
	{ JEY: 'Jersey', label: 'Jersey' },
	{ JOR: 'Jordan', label: 'Jordan' },
	{ KAZ: 'Kazakhstan', label: 'Kazakhstan' },
	{ KEN: 'Kenya', label: 'Kenya' },
	{ KIR: 'Kiribati', label: 'Kiribati' },
	{ PRK: 'Korea the Democratic People s Republic of', label: 'Korea the Democratic Peoples Republic of ' },
	{ KOR: 'Korea (the Republic of)', label: 'Korea (the Republic of)' },
	{ KWT: 'Kuwait', label: 'Kuwait' },
	{ KGZ: 'Kyrgyzstan', label: 'Kyrgyzstan' },
	{ LAO: "Lao People's Democratic Republic (the)", label: "Lao People's Democratic Republic (the)" },
	{ LVA: 'Latvia', label: 'Latvia' },
	{ LBN: 'Lebanon', label: 'Lebanon' },
	{ LSO: 'Lesotho', label: 'Lesotho' },
	{ LBR: 'Liberia', label: 'Liberia' },
	{ LBY: 'Libya', label: 'Libya' },
	{ LIE: 'Liechtenstein', label: 'Liechtenstein' },
	{ LTU: 'Lithuania', label: 'Lithuania' },
	{ LUX: 'Luxembourg', label: 'Luxembourg' },
	{ MAC: 'Macao', label: 'Macao' },
	{ MDG: 'Madagascar', label: 'Madagascar' },
	{ MWI: 'Malawi', label: 'Malawi' },
	{ MYS: 'Malaysia', label: 'Malaysia' },
	{ MDV: 'Maldives', label: 'Maldives' },
	{ MLI: 'Mali', label: 'Mali' },
	{ MLT: 'Malta', label: 'Malta' },
	{ MHL: 'Marshall Islands (the)', label: 'Marshall Islands (the)' },
	{ MTQ: 'Martinique', label: 'Martinique' },
	{ MRT: 'Mauritania', label: 'Mauritania' },
	{ MUS: 'Mauritius', label: 'Mauritius' },
	{ MYT: 'Mayotte', label: 'Mayotte' },
	{ MEX: 'Mexico', label: 'Mexico' },
	{ FSM: 'Micronesia (Federated States of)', label: 'Micronesia (Federated States of)' },
	{ MDA: 'Moldova (the Republic of)', label: 'Moldova (the Republic of)' },
	{ MCO: 'Monaco', label: 'Monaco' },
	{ MNG: 'Mongolia', label: 'Mongolia' },
	{ MNE: 'Montenegro', label: 'Montenegro' },
	{ MSR: 'Montserrat', label: 'Montserrat' },
	{ MAR: 'Morocco', label: 'Morocco' },
	{ MOZ: 'Mozambique', label: 'Mozambique' },
	{ MMR: 'Myanmar', label: 'Myanmar' },
	{ NAM: 'Namibia', label: 'Namibia' },
	{ NRU: 'Nauru', label: 'Nauru' },
	{ NPL: 'Nepal', label: 'Nepal' },
	{ NLD: 'Netherlands (the)', label: 'Netherlands (the)' },
	{ NCL: 'New Caledonia', label: 'New Caledonia' },
	{ NZL: 'New Zealand', label: 'New Zealand' },
	{ NIC: 'Nicaragua', label: 'Nicaragua' },
	{ NER: 'Niger (the)', label: 'Niger (the)' },
	{ NGA: 'Nigeria', label: 'Nigeria' },
	{ NIU: 'Niue', label: 'Niue' },
	{ NFK: 'Norfolk Island', label: 'Norfolk Island' },
	{ MNP: 'Northern Mariana Islands (the)', label: 'Northern Mariana Islands (the)' },
	{ NOR: 'Norway', label: 'Norway' },
	{ OMN: 'Oman', label: 'Oman' },
	{ PAK: 'Pakistan', label: 'Pakistan' },
	{ PLW: 'Palau', label: 'Palau' },
	{ PSE: 'Palestine State of', label: 'Palestine State of' },
	{ PAN: 'Panama', label: 'Panama' },
	{ PNG: 'Papua New Guinea', label: 'Papua New Guinea' },
	{ PRY: 'Paraguay', label: 'Paraguay' },
	{ PER: 'Peru', label: 'Peru' },
	{ PHL: 'Philippines (the)', label: 'Philippines (the)' },
	{ PCN: 'Pitcairn', label: 'Pitcairn' },
	{ POL: 'Poland', label: 'Poland' },
	{ PRT: 'Portugal', label: 'Portugal' },
	{ PRI: 'Puerto Rico', label: 'Puerto Rico' },
	{ QAT: 'Qatar', label: 'Qatar' },
	{ MKD: 'Republic of North Macedonia', label: 'Republic of North Macedonia' },
	{ ROU: 'Romania', label: 'Romania' },
	{ RUS: 'Russian Federation (the)', label: 'Russian Federation (the)' },
	{ RWA: 'Rwanda', label: 'Rwanda' },
	{ REU: 'Réunion', label: 'Réunion' },
	{ BLM: 'Saint Barthélemy', label: 'Saint Barthélemy' },
	{ SHN: 'Saint Helena Ascension and Tristan da Cunha', label: 'Saint Helena Ascension and Tristan da Cunha' },
	{ KNA: 'Saint Kitts and Nevis', label: 'Saint Kitts and Nevis' },
	{ LCA: 'Saint Lucia', label: 'Saint Lucia' },
	{ MAF: 'Saint Martin (French part)', label: 'Saint Martin (French part)' },
	{ SPM: 'Saint Pierre and Miquelon', label: 'Saint Pierre and Miquelon' },
	{ VCT: 'Saint Vincent and the Grenadines', label: 'Saint Vincent and the Grenadines' },
	{ WSM: 'Samoa', label: 'Samoa' },
	{ SMR: 'San Marino', label: 'San Marino' },
	{ STP: 'Sao Tome and Principe', label: 'Sao Tome and Principe' },
	{ SAU: 'Saudi Arabia', label: 'Saudi Arabia' },
	{ SEN: 'Senegal', label: 'Senegal' },
	{ SRB: 'Serbia', label: 'Serbia' },
	{ SYC: 'Seychelles', label: 'Seychelles' },
	{ SLE: 'Sierra Leone', label: 'Sierra Leone' },
	{ SGP: 'Singapore', label: 'Singapore' },
	{ SXM: 'Sint Maarten (Dutch part)', label: 'Sint Maarten (Dutch part)' },
	{ SVK: 'Slovakia', label: 'Slovakia' },
	{ SVN: 'Slovenia', label: 'Slovenia' },
	{ SLB: 'Solomon Islands', label: 'Solomon Islands' },
	{ SOM: 'Somalia', label: 'Somalia' },
	{ ZAF: 'South Africa', label: 'South Africa' },
	{ SGS: 'South Georgia and the South Sandwich Islands', label: 'South Georgia and the South Sandwich Islands' },
	{ SSD: 'South Sudan', label: 'South Sudan' },
	{ ESP: 'Spain', label: 'Spain' },
	{ LKA: 'Sri Lanka', label: 'Sri Lanka' },
	{ SDN: 'Sudan (the)', label: 'Sudan (the)' },
	{ SUR: 'Suriname', label: 'Suriname' },
	{ SJM: 'Svalbard and Jan Mayen', label: 'Svalbard and Jan Mayen' },
	{ SWE: 'Sweden', label: 'Sweden' },
	{ CHE: 'Switzerland', label: 'Switzerland' },
	{ SYR: 'Syrian Arab Republic', label: 'Syrian Arab Republic' },
	{ TWN: 'Taiwan', label: 'Taiwan' },
	{ TJK: 'Tajikistan', label: 'Tajikistan' },
	{ TZA: 'Tanzania United Republic of', label: 'Tanzania United Republic of' },
	{ THA: 'Thailand', label: 'Thailand' },
	{ TLS: 'Timor-Leste', label: 'Timor-Leste' },
	{ TGO: 'Togo', label: 'Togo' },
	{ TKL: 'Tokelau', label: 'Tokelau' },
	{ TON: 'Tonga', label: 'Tonga' },
	{ TTO: 'Trinidad and Tobago', label: 'Trinidad and Tobago' },
	{ TUN: 'Tunisia', label: 'Tunisia' },
	{ TUR: 'Turkey', label: 'Turkey' },
	{ TKM: 'Turkmenistan', label: 'Turkmenistan' },
	{ TCA: 'Turks and Caicos Islands (the)', label: 'Turks and Caicos Islands (the)' },
	{ TUV: 'Tuvalu', label: 'Tuvalu' },
	{ UGA: 'Uganda', label: 'Uganda' },
	{ UKR: 'Ukraine', label: 'Ukraine' },
	{ ARE: 'United Arab Emirates (the)', label: 'United Arab Emirates (the)' },
	{
		GBR: 'United Kingdom of Great Britain and Northern Ireland (the)',
		label: 'United Kingdom of Great Britain and Northern Ireland (the)'
	},
	{ UMI: 'United States Minor Outlying Islands (the)', label: 'United States Minor Outlying Islands (the)' },
	{ USA: 'United States of America (the)', label: 'United States of America (the)' },
	{ URY: 'Uruguay', label: 'Uruguay' },
	{ UZB: 'Uzbekistan', label: 'Uzbekistan' },
	{ VUT: 'Vanuatu', label: 'Vanuatu' },
	{ VEN: 'Venezuela (Bolivarian Republic of)', label: 'Venezuela (Bolivarian Republic of)' },
	{ VNM: 'Viet Nam', label: 'Viet Nam' },
	{ VGB: 'Virgin Islands (British)', label: 'Virgin Islands (British)' },
	{ VIR: 'Virgin Islands (U.S.)', label: 'Virgin Islands (U.S.)' },
	{ WLF: 'Wallis and Futuna', label: 'Wallis and Futuna' },
	{ ESH: 'Western Sahazra', label: 'Western Sahara' },
	{ YEM: 'Yemen', label: 'Yemen' },
	{ ZMB: 'Zambia', label: 'Zambia' },
	{ ZWE: 'Zimbabwe', label: 'Zimbabwe' },
	{ ALA: 'Åland Islands', label: 'Åland Islands' }
];

export const countryCodeTwoLetters = [
	{ code: 'AF', name: 'Afghanistan' },
	{ code: 'AL', name: 'Albania' },
	{ code: 'DZ', name: 'Algeria' },
	{ code: 'AS', name: 'American Samoa' },
	{ code: 'AD', name: 'Andorra' },
	{ code: 'AO', name: 'Angola' },
	{ code: 'AI', name: 'Anguilla' },
	{ code: 'AQ', name: 'Antarctica' },
	{ code: 'AG', name: 'Antigua and Barbuda' },
	{ code: 'AR', name: 'Argentina' },
	{ code: 'AM', name: 'Armenia' },
	{ code: 'AW', name: 'Aruba' },
	{ code: 'AU', name: 'Australia' },
	{ code: 'AT', name: 'Austria' },
	{ code: 'AZ', name: 'Azerbaijan' },
	{ code: 'BS', name: 'Bahamas (the)' },
	{ code: 'BH', name: 'Bahrain' },
	{ code: 'BD', name: 'Bangladesh' },
	{ code: 'BB', name: 'Barbados' },
	{ code: 'BY', name: 'Belarus' },
	{ code: 'BE', name: 'Belgium' },
	{ code: 'BZ', name: 'Belize' },
	{ code: 'BJ', name: 'Benin' },
	{ code: 'BM', name: 'Bermuda' },
	{ code: 'BT', name: 'Bhutan' },
	{ code: 'BO', name: 'Bolivia (Plurinational State of)' },
	{ code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba' },
	{ code: 'BA', name: 'Bosnia and Herzegovina' },
	{ code: 'BW', name: 'Botswana' },
	{ code: 'BV', name: 'Bouvet Island' },
	{ code: 'BR', name: 'Brazil' },
	{ code: 'IO', name: 'British Indian Ocean Territory (the)' },
	{ code: 'BN', name: 'Brunei Darussalam' },
	{ code: 'BG', name: 'Bulgaria' },
	{ code: 'BF', name: 'Burkina Faso' },
	{ code: 'BI', name: 'Burundi' },
	{ code: 'CV', name: 'Cabo Verde' },
	{ code: 'KH', name: 'Cambodia' },
	{ code: 'CM', name: 'Cameroon' },
	{ code: 'CA', name: 'Canada' },
	{ code: 'KY', name: 'Cayman Islands (the)' },
	{ code: 'CF', name: 'Central African Republic (the)' },
	{ code: 'TD', name: 'Chad' },
	{ code: 'CL', name: 'Chile' },
	{ code: 'CN', name: 'China' },
	{ code: 'CX', name: 'Christmas Island' },
	{ code: 'CC', name: 'Cocos (Keeling) Islands (the)' },
	{ code: 'CO', name: 'Colombia' },
	{ code: 'KM', name: 'Comoros (the)' },
	{ code: 'CD', name: 'Congo (the Democratic Republic of the)' },
	{ code: 'CG', name: 'Congo (the)' },
	{ code: 'CK', name: 'Cook Islands (the)' },
	{ code: 'CR', name: 'Costa Rica' },
	{ code: 'HR', name: 'Croatia' },
	{ code: 'CU', name: 'Cuba' },
	{ code: 'CW', name: 'Curaçao' },
	{ code: 'CY', name: 'Cyprus' },
	{ code: 'CZ', name: 'Czechia' },
	{ code: 'CI', name: "Côte d'Ivoire" },
	{ code: 'DK', name: 'Denmark' },
	{ code: 'DJ', name: 'Djibouti' },
	{ code: 'DM', name: 'Dominica' },
	{ code: 'DO', name: 'Dominican Republic (the)' },
	{ code: 'EC', name: 'Ecuador' },
	{ code: 'EG', name: 'Egypt' },
	{ code: 'SV', name: 'El Salvador' },
	{ code: 'GQ', name: 'Equatorial Guinea' },
	{ code: 'ER', name: 'Eritrea' },
	{ code: 'EE', name: 'Estonia' },
	{ code: 'SZ', name: 'Eswatini' },
	{ code: 'ET', name: 'Ethiopia' },
	{ code: 'FK', name: 'Falkland Islands (the) [Malvinas]' },
	{ code: 'FO', name: 'Faroe Islands (the)' },
	{ code: 'FJ', name: 'Fiji' },
	{ code: 'FI', name: 'Finland' },
	{ code: 'FR', name: 'France' },
	{ code: 'GF', name: 'French Guiana' },
	{ code: 'PF', name: 'French Polynesia' },
	{ code: 'TF', name: 'French Southern Territories (the)' },
	{ code: 'GA', name: 'Gabon' },
	{ code: 'GM', name: 'Gambia (the)' },
	{ code: 'GE', name: 'Georgia' },
	{ code: 'DE', name: 'Germany' },
	{ code: 'GH', name: 'Ghana' },
	{ code: 'GI', name: 'Gibraltar' },
	{ code: 'GR', name: 'Greece' },
	{ code: 'GL', name: 'Greenland' },
	{ code: 'GD', name: 'Grenada' },
	{ code: 'GP', name: 'Guadeloupe' },
	{ code: 'GU', name: 'Guam' },
	{ code: 'GT', name: 'Guatemala' },
	{ code: 'GG', name: 'Guernsey' },
	{ code: 'GN', name: 'Guinea' },
	{ code: 'GW', name: 'Guinea-Bissau' },
	{ code: 'GY', name: 'Guyana' },
	{ code: 'HT', name: 'Haiti' },
	{ code: 'HM', name: 'Heard Island and McDonald Islands' },
	{ code: 'VA', name: 'Holy See (the)' },
	{ code: 'HN', name: 'Honduras' },
	{ code: 'HK', name: 'Hong Kong' },
	{ code: 'HU', name: 'Hungary' },
	{ code: 'IS', name: 'Iceland' },
	{ code: 'IN', name: 'India' },
	{ code: 'ID', name: 'Indonesia' },
	{ code: 'IR', name: 'Iran (Islamic Republic of)' },
	{ code: 'IQ', name: 'Iraq' },
	{ code: 'IE', name: 'Ireland' },
	{ code: 'IM', name: 'Isle of Man' },
	{ code: 'IL', name: 'Israel' },
	{ code: 'IT', name: 'Italy' },
	{ code: 'JM', name: 'Jamaica' },
	{ code: 'JP', name: 'Japan' },
	{ code: 'JE', name: 'Jersey' },
	{ code: 'JO', name: 'Jordan' },
	{ code: 'KZ', name: 'Kazakhstan' },
	{ code: 'KE', name: 'Kenya' },
	{ code: 'KI', name: 'Kiribati' },
	{ code: 'KP', name: "Korea (the Democratic People's Republic of)" },
	{ code: 'KR', name: 'Korea (the Republic of)' },
	{ code: 'KW', name: 'Kuwait' },
	{ code: 'KG', name: 'Kyrgyzstan' },
	{ code: 'LA', name: "Lao People's Democratic Republic (the)" },
	{ code: 'LV', name: 'Latvia' },
	{ code: 'LB', name: 'Lebanon' },
	{ code: 'LS', name: 'Lesotho' },
	{ code: 'LR', name: 'Liberia' },
	{ code: 'LY', name: 'Libya' },
	{ code: 'LI', name: 'Liechtenstein' },
	{ code: 'LT', name: 'Lithuania' },
	{ code: 'LU', name: 'Luxembourg' },
	{ code: 'MO', name: 'Macao' },
	{ code: 'MG', name: 'Madagascar' },
	{ code: 'MW', name: 'Malawi' },
	{ code: 'MY', name: 'Malaysia' },
	{ code: 'MV', name: 'Maldives' },
	{ code: 'ML', name: 'Mali' },
	{ code: 'MT', name: 'Malta' },
	{ code: 'MH', name: 'Marshall Islands (the)' },
	{ code: 'MQ', name: 'Martinique' },
	{ code: 'MR', name: 'Mauritania' },
	{ code: 'MU', name: 'Mauritius' },
	{ code: 'YT', name: 'Mayotte' },
	{ code: 'MX', name: 'Mexico' },
	{ code: 'FM', name: 'Micronesia (Federated States of)' },
	{ code: 'MD', name: 'Moldova (the Republic of)' },
	{ code: 'MC', name: 'Monaco' },
	{ code: 'MN', name: 'Mongolia' },
	{ code: 'ME', name: 'Montenegro' },
	{ code: 'MS', name: 'Montserrat' },
	{ code: 'MA', name: 'Morocco' },
	{ code: 'MZ', name: 'Mozambique' },
	{ code: 'MM', name: 'Myanmar' },
	{ code: 'NA', name: 'Namibia' },
	{ code: 'NR', name: 'Nauru' },
	{ code: 'NP', name: 'Nepal' },
	{ code: 'NL', name: 'Netherlands (the)' },
	{ code: 'NC', name: 'New Caledonia' },
	{ code: 'NZ', name: 'New Zealand' },
	{ code: 'NI', name: 'Nicaragua' },
	{ code: 'NE', name: 'Niger (the)' },
	{ code: 'NG', name: 'Nigeria' },
	{ code: 'NU', name: 'Niue' },
	{ code: 'NF', name: 'Norfolk Island' },
	{ code: 'MP', name: 'Northern Mariana Islands (the)' },
	{ code: 'NO', name: 'Norway' },
	{ code: 'OM', name: 'Oman' },
	{ code: 'PK', name: 'Pakistan' },
	{ code: 'PW', name: 'Palau' },
	{ code: 'PS', name: 'Palestine, State of' },
	{ code: 'PA', name: 'Panama' },
	{ code: 'PG', name: 'Papua New Guinea' },
	{ code: 'PY', name: 'Paraguay' },
	{ code: 'PE', name: 'Peru' },
	{ code: 'PH', name: 'Philippines (the)' },
	{ code: 'PN', name: 'Pitcairn' },
	{ code: 'PL', name: 'Poland' },
	{ code: 'PT', name: 'Portugal' },
	{ code: 'PR', name: 'Puerto Rico' },
	{ code: 'QA', name: 'Qatar' },
	{ code: 'MK', name: 'Republic of North Macedonia' },
	{ code: 'RO', name: 'Romania' },
	{ code: 'RU', name: 'Russian Federation (the)' },
	{ code: 'RW', name: 'Rwanda' },
	{ code: 'RE', name: 'Réunion' },
	{ code: 'BL', name: 'Saint Barthélemy' },
	{ code: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha' },
	{ code: 'KN', name: 'Saint Kitts and Nevis' },
	{ code: 'LC', name: 'Saint Lucia' },
	{ code: 'MF', name: 'Saint Martin (French part)' },
	{ code: 'PM', name: 'Saint Pierre and Miquelon' },
	{ code: 'VC', name: 'Saint Vincent and the Grenadines' },
	{ code: 'WS', name: 'Samoa' },
	{ code: 'SM', name: 'San Marino' },
	{ code: 'ST', name: 'Sao Tome and Principe' },
	{ code: 'SA', name: 'Saudi Arabia' },
	{ code: 'SN', name: 'Senegal' },
	{ code: 'RS', name: 'Serbia' },
	{ code: 'SC', name: 'Seychelles' },
	{ code: 'SL', name: 'Sierra Leone' },
	{ code: 'SG', name: 'Singapore' },
	{ code: 'SX', name: 'Sint Maarten (Dutch part)' },
	{ code: 'SK', name: 'Slovakia' },
	{ code: 'SI', name: 'Slovenia' },
	{ code: 'SB', name: 'Solomon Islands' },
	{ code: 'SO', name: 'Somalia' },
	{ code: 'ZA', name: 'South Africa' },
	{ code: 'GS', name: 'South Georgia and the South Sandwich Islands' },
	{ code: 'SS', name: 'South Sudan' },
	{ code: 'ES', name: 'Spain' },
	{ code: 'LK', name: 'Sri Lanka' },
	{ code: 'SD', name: 'Sudan (the)' },
	{ code: 'SR', name: 'Suriname' },
	{ code: 'SJ', name: 'Svalbard and Jan Mayen' },
	{ code: 'SE', name: 'Sweden' },
	{ code: 'CH', name: 'Switzerland' },
	{ code: 'SY', name: 'Syrian Arab Republic' },
	{ code: 'TW', name: 'Taiwan' },
	{ code: 'TJ', name: 'Tajikistan' },
	{ code: 'TZ', name: 'Tanzania, United Republic of' },
	{ code: 'TH', name: 'Thailand' },
	{ code: 'TL', name: 'Timor-Leste' },
	{ code: 'TG', name: 'Togo' },
	{ code: 'TK', name: 'Tokelau' },
	{ code: 'TO', name: 'Tonga' },
	{ code: 'TT', name: 'Trinidad and Tobago' },
	{ code: 'TN', name: 'Tunisia' },
	{ code: 'TR', name: 'Turkey' },
	{ code: 'TM', name: 'Turkmenistan' },
	{ code: 'TC', name: 'Turks and Caicos Islands (the)' },
	{ code: 'TV', name: 'Tuvalu' },
	{ code: 'UG', name: 'Uganda' },
	{ code: 'UA', name: 'Ukraine' },
	{ code: 'AE', name: 'United Arab Emirates (the)' },
	{ code: 'GB', name: 'United Kingdom of Great Britain and Northern Ireland (the)' },
	{ code: 'UM', name: 'United States Minor Outlying Islands (the)' },
	{ code: 'US', name: 'United States of America (the)' },
	{ code: 'UY', name: 'Uruguay' },
	{ code: 'UZ', name: 'Uzbekistan' },
	{ code: 'VU', name: 'Vanuatu' },
	{ code: 'VE', name: 'Venezuela (Bolivarian Republic of)' },
	{ code: 'VN', name: 'Viet Nam' },
	{ code: 'VG', name: 'Virgin Islands (British)' },
	{ code: 'VI', name: 'Virgin Islands (U.S.)' },
	{ code: 'WF', name: 'Wallis and Futuna' },
	{ code: 'EH', name: 'Western Sahara' },
	{ code: 'YE', name: 'Yemen' },
	{ code: 'ZM', name: 'Zambia' },
	{ code: 'ZW', name: 'Zimbabwe' },
	{ code: 'AX', name: 'Åland Islands' }
];
