export const mainCategories = [
  "Electrician",
  "Plumber",
  "Carpenter",
  "Tiler",
  "Painter",
  "Plasterer",
  "Landscapper",
  "Labourer",
  "Bricklayer",
  "Lawn Mowing",
  "Builder",
];

export const allCategories = [
  "Air Conditioning",
  "Antenna",
  "Audio Visual & Computers",
  "Appliance Repair",
  "Asbestos And Mold Services",
  "Bathroom Renovation",
  "Bob Cat Services",
  "Bricklayer",
  "Builder",
  "Builders & Contractors",
  "Building Inspections/certifiers",
  "Cabinet & Kitchen makers",
  "Carpenter",
  "Carpet & Upholstery cleaning",
  "Ceilings",
  "Civil Construction",
  "Cleaning Services",
  "Concrete Services",
  "Counter & Bench tops",
  "Demolition Contractors",
  "Doors",
  "Drainage",
  "Dry-wall Wet wall & Plastering",
  "Electrician",
  "Equipment Hire",
  "Excavation & Digger Hire",
  "Fencing",
  "Flooring & Carpet",
  "Fly Screens",
  "Garage Doors",
  "Gas Fitters",
  "Gas & Glazing",
  "Gutters & Down pipes",
  "Handyman Services",
  "Heating Systems",
  "Home Inspection",
  "Home Security",
  "Insulation",
  "Irrigation & Rectic systems",
  "Joinery",
  "Labourer",
  "Labourer & General Operative",
  "Landscaper",
  "Landscaping",
  "Lawn Mowing",
  "Lawn & Garden Care",
  "Lock Smith",
  "Maintenance",
  "Metal fabrication & Welding",
  "Painter",
  "Painting & Decorating",
  "Paving",
  "Pest Control",
  "Plasterer",
  "Plumber",
  "Plumbing & Heating",
  "Power Washing",
  "Removal & Delivery service",
  "Retaining Walls",
  "Roofing",
  "Septic tanks & Wells",
  "Sewer Services",
  "Silicon & Sealing services",
  "Solar Panels",
  "Stone Mason",
  "Swimming Pools",
  "Tiler",
  "Tiling",
  "Timber Flooring",
  "Torch On Felt",
  "Tree Services/Aborists",
  "Wall Cladding/Slide",
  "Waste Removal services",
  "Waterproofing",
  "Window Tinting",
  "Windows",
];
