// GENERATE_ACCESS_TOKEN
export const GENERATE_ACCESS_TOKEN_REQUEST = "GENERATE_ACCESS_TOKEN_REQUEST";
export const GENERATE_ACCESS_TOKEN_SUCCESS = "GENERATE_ACCESS_TOKEN_SUCCESS";
export const GENERATE_ACCESS_TOKEN_RESET = "GENERATE_ACCESS_TOKEN_RESET";
export const GENERATE_ACCESS_TOKEN_FAILURE = "GENERATE_ACCESS_TOKEN_FAILURE";

// UPDATE_ACCESS_TOKEN
export const UPDATE_ACCESS_TOKEN_REQUEST = "UPDATE_ACCESS_TOKEN_REQUEST";
export const UPDATE_ACCESS_TOKEN_SUCCESS = "UPDATE_ACCESS_TOKEN_SUCCESS";
export const UPDATE_ACCESS_TOKEN_RESET = "UPDATE_ACCESS_TOKEN_RESET";
export const UPDATE_ACCESS_TOKEN_FAILURE = "UPDATE_ACCESS_TOKEN_FAILURE";

// OPT_REGISTER
export const OPT_REGISTER_REQUEST = "OPT_REGISTER_REQUEST";
export const OPT_REGISTER_SUCCESS = "OPT_REGISTER_SUCCESS";
export const OPT_REGISTER_RESET = "OPT_REGISTER_RESET";
export const OPT_REGISTER_FAILURE = "OPT_REGISTER_FAILURE";

// OTP_LOGIN
export const OTP_LOGIN_REQUEST = "OTP_LOGIN_REQUEST";
export const OTP_LOGIN_SUCCESS = "OTP_LOGIN_SUCCESS";
export const OTP_LOGIN_RESET = "OTP_LOGIN_RESET";
export const OTP_LOGIN_FAILURE = "OTP_LOGIN_FAILURE";

// TEST_VERIFY_OTP
export const TEST_VERIFY_OTP_REQUEST = "TEST_VERIFY_OTP_REQUEST";

// VERIFY_OTP
export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_RESET = "VERIFY_OTP_RESET";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";

// COOKIE_POLICY
export const COOKIE_POLICY = "COOKIE_POLICY";

// FaceBook login
export const FACEBOOK_LOGIN_REQUEST = "FACEBOOK_LOGIN_REQUEST";
export const FACEBOOK_LOGIN_SUCCESS = "FACEBOOK_LOGIN_SUCCESS";
export const FACEBOOK_LOGIN_RESET = "FACEBOOK_LOGIN_RESET";
export const FACEBOOK_LOGIN_FAILURE = "FACEBOOK_LOGIN_FAILURE";
//sign up otp
export const RESET_SIGNUP_OTP_REQUEST = "RESET_SIGNUP_OTP_REQUEST";
export const RESET_SIGNUP_OTP_SUCCESS = "RESET_SIGNUP_OTP_SUCCESS";
export const RESET_SIGNUP_OTP_RESET = "RESET_SIGNUP_OTP_RESET";
export const RESET_SIGNUP_OTP_FAILURE = "RESET_SIGNUP_OTP_FAILURE";
//login otp
export const RESET_LOGIN_OTP_REQUEST = "RESET_LOGIN_OTP_REQUEST";
export const RESET_LOGIN_OTP_SUCCESS = "RESET_LOGIN_OTP_SUCCESS";
export const RESET_LOGIN_OTP_RESET = "RESET_LOGIN_OTP_RESET";
export const RESET_LOGIN_OTP_FAILURE = "RESET_LOGIN_OTP_FAILURE";

//user profile update
export const UPDATE_PROFILE_VERIFICATION_REQUEST =
  "UPDATE_PROFILE_VERIFICATION_REQUEST";
export const UPDATE_PROFILE_VERIFICATION_SUCCESS =
  "UPDATE_PROFILE_VERIFICATION_SUCCESS";
export const UPDATE_PROFILE_VERIFICATION_RESET =
  "UPDATE_PROFILE_VERIFICATION_RESET";
export const UPDATE_PROFILE_VERIFICATION_FAILURE =
  "UPDATE_PROFILE_VERIFICATION_FAILURE";
export const SUBMIT_FOR_APPROVAL = "SUBMIT_FOR_APPROVAL";
export const SUBMIT_FOR_APPROVAL_SUCCESS = "SUBMIT_FOR_APPROVAL_SUCCESS";
export const SUBMIT_FOR_APPROVAL_RESET = "SUBMIT_FOR_APPROVAL_RESET";
export const SUBMIT_FOR_APPROVAL_FAILURE = "SUBMIT_FOR_APPROVAL_FAILURE";

//get user
export const GET_PROFILE_INFORMATION_REQUEST =
  "GET_PROFILE_INFORMATION_REQUEST";
export const GET_PROFILE_INFORMATION_SUCCESS =
  "GET_PROFILE_INFORMATION_SUCCESS";
export const GET_PROFILE_INFORMATION_RESET = "GET_PROFILE_INFORMATION_RESET";
export const GET_PROFILE_INFORMATION_FAILURE =
  "GET_PROFILE_INFORMATION_FAILURE";

// profile steps

export const PROFILE_STEPS_REQUEST = "PROFILE_STEPS_REQUEST";
export const PROFILE_STEPS_SUCCESS = "PROFILE_STEPS_SUCCESS";
export const PROFILE_STEPS_RESET = "PROFILE_STEPS_RESET";
export const PROFILE_STEPS_FAILURE = "PROFILE_STEPS_FAILURE";

// profile register

export const PROFILE_PROVIDER_REGISTER_REQUEST =
  "PROFILE_PROVIDER_REGISTER_REQUEST";
export const PROFILE_PROVIDER_REGISTER_SUCCESS =
  "PROFILE_PROVIDER_REGISTER_SUCCESS";
export const PROFILE_PROVIDER_REGISTER_RESET =
  "PROFILE_PROVIDER_REGISTER_RESET";
export const PROFILE_PROVIDER_REGISTER_FAILURE =
  "PROFILE_PROVIDER_REGISTER_FAILURE";

//get provider profile
// export const GET_PROVIDER_PROFILE_REQUEST = 'GET_PROVIDER_PROFILE_REQUEST';
// export const GET_PROVIDER_PROFILE_SUCCESS = 'GET_PROVIDER_PROFILE_SUCCESS';
// export const GET_PROVIDER_PROFILE_RESET = 'GET_PROVIDER_PROFILE_RESET';
// export const GET_PROVIDER_PROFILE_FAILURE = 'GET_PROVIDER_PROFILE_FAILURE';

//provider-get-business-detail

export const GET_BUSINESSS_DETAILS_REQUEST = "GET_BUSINESSS_DETAILS_REQUEST";
export const GET_BUSINESSS_DETAILS_SUCCESS = "GET_BUSINESSS_DETAILS_SUCCESS";
export const GET_BUSINESSS_DETAILS_RESET = "GET_BUSINESSS_DETAILS_RESET";
export const GET_BUSINESSS_DETAILS_FAILURE = "GET_BUSINESSS_DETAILS_FAILURE";

//business details update
export const BUSINESSS_DETAILS_UPDATE_REQUEST =
  "BUSINESSS_DETAILS_UPDATE_REQUEST";
export const BUSINESSS_DETAILS_UPDATE_SUCCESS =
  "BUSINESSS_DETAILS_UPDATE_SUCCESS";
export const BUSINESSS_DETAILS_UPDATE_RESET = "BUSINESSS_DETAILS_UPDATE_RESET";
export const BUSINESSS_DETAILS_UPDATE_FAILURE = "BUSINESSS_DETAILS_FAILURE";

//image gallary list

export const PROVIDER_GALLARY_LIST_REQUEST = "PROVIDER_GALLARY_LIST__REQUEST";
export const PROVIDER_GALLARY_LIST_SUCCESS = "PROVIDER_GALLARY_LIST__SUCCESS";
export const PROVIDER_GALLARY_LIST_RESET = "PROVIDER_GALLARY_LIST__RESET";
export const PROVIDER_GALLARY_LIST_FAILURE = "PROVIDER_GALLARY_LIST_FAILURE";

//image gallary Delete
export const PROVIDER_GALLARY_DELETE_REQUEST =
  "PROVIDER_GALLARY_DELETE__REQUEST";
export const PROVIDER_GALLARY_DELETE_SUCCESS =
  "PROVIDER_GALLARY_DELETE__SUCCESS";
export const PROVIDER_GALLARY_DELETE_RESET = "PROVIDER_GALLARY_DELETE__RESET";
export const PROVIDER_GALLARY_DELETE_FAILURE =
  "PROVIDER_GALLARY_DELETE_FAILURE";

//image upload
export const IMAGE_UPLOAD_REQUEST = "IMAGE_UPLOAD__REQUEST";
export const IMAGE_UPLOAD_SUCCESS = "IMAGE_UPLOAD__SUCCESS";
export const IMAGE_UPLOAD_RESET = "IMAGE_UPLOAD__RESET";
export const IMAGE_UPLOAD_FAILURE = "IMAGE_UPLOAD_FAILURE";

// /get-services-list

export const GET_SERVICE_LIST_REQUEST = "GET_SERVICE_LIST__REQUEST";
export const GET_SERVICE_LIST_SUCCESS = "GET_SERVICE_LIST__SUCCESS";
export const GET_SERVICE_LIST_RESET = "GET_SERVICE_LIST__RESET";
export const GET_SERVICE_LIST_FAILURE = "GET_SERVICE_LIST_FAILURE";

///user-get-address

export const GET_USER_ADDRESS_REQUEST = "GET_USER_ADDRESS__REQUEST";
export const GET_USER_ADDRESS_SUCCESS = "GET_USER_ADDRESS__SUCCESS";
export const GET_USER_ADDRESS_RESET = "GET_USER_ADDRESS__RESET";
export const GET_USER_ADDRESS_FAILURE = "GET_USER_ADDRESS_FAILURE";

//get provider address

export const GET_PROVIDER_ADDRESS_REQUEST = "GET_PROVIDER_ADDRESS__REQUEST";
export const GET_PROVIDER_ADDRESS_SUCCESS = "GET_PROVIDER_ADDRESS__SUCCESS";
export const GET_PROVIDER_ADDRESS_RESET = "GET_PROVIDER_ADDRESS__RESET";
export const GET_PROVIDER_ADDRESS_FAILURE = "GET_PROVIDER_ADDRESS_FAILURE";

//popup 2 and 3

export const PROVIDER_ASSIGN_POP3_REQUEST = "PROVIDER_ASSIGN_POP3__REQUEST";
export const PROVIDER_ASSIGN_POP3_SUCCESS = "PROVIDER_ASSIGN_POP3__SUCCESS";
export const PROVIDER_ASSIGN_POP3_RESET = "PROVIDER_ASSIGN_POP3__RESET";
export const PROVIDER_ASSIGN_POP3_FAILURE = "PROVIDER_ASSIGN_POP3_FAILURE";

//loggout
export const LOGOUT__REQUEST = "LOGOUT__REQUEST";
export const LOGOUT__SUCCESS = "LOGOUT__SUCCESS";
export const LOGOUT__RESET = "LOGOUT__RESET";
export const LOGOUT__FAILURE = "LOGOUT__FAILURE ";

//NewUSerStartup profile

export const SIGNUP_USER_ENTER_NAME_REQUEST = "SIGNUP_USER_ENTER_NAME__REQUEST";
export const SIGNUP_USER_ENTER_NAME_SUCCESS = "SIGNUP_USER_ENTER_NAME__SUCCESS";
export const SIGNUP_USER_ENTER_NAME_RESET = "SIGNUP_USER_ENTER_NAME__RESET";
export const SIGNUP_USER_ENTER_NAME_FAILURE = "SIGNUP_USER_ENTER_NAME_FAILURE";
//NewUSerCompletion profile

export const SIGNUP_USER_COMPLETION_REQUEST = "SIGNUP_USER_COMPLETION__REQUEST";
export const SIGNUP_USER_COMPLETION_SUCCESS = "SIGNUP_USER_COMPLETION__SUCCESS";
export const SIGNUP_USER_COMPLETION_RESET = "SIGNUP_USER_COMPLETION__RESET";
export const SIGNUP_USER_COMPLETION_FAILURE = "SIGNUP_USER_COMPLETION_FAILURE";

//TradieTV video search

export const TRADIETV_VIDEO_SEARCH_REQUEST = "TRADIETV_VIDEO_SEARCH_REQUEST";
export const TRADIETV_VIDEO_SEARCH_SUCCESS = "TRADIETV_VIDEO_SEARCH_SUCCESS";
export const TRADIETV_VIDEO_SEARCH_RESET = "TRADIETV_VIDEO_SEARCH_RESET";
export const TRADIETV_VIDEO_SEARCH_FAILURE = "TRADIETV_VIDEO_SEARCH_FAILURE";

//GET_COUNTRY_LIST

export const GET_COUNTRY_LIST_REQUEST = "GET_COUNTRY_LIST_REQUEST";
export const GET_COUNTRY_LIST_SUCCESS = "GET_COUNTRY_LIST_SUCCESS";
export const GET_COUNTRY_LIST_RESET = "GET_COUNTRY_LIST_RESET";
export const GET_COUNTRY_LIST_FAILURE = "GET_COUNTRY_LIST_FAILURE";

export const OPT_STATE_CHANGE = "OPT_STATE_CHANGE";

export const OPT_STATE_REG_CHANGE = "OPT_STATE_REG_CHANGE";

//UPLOAD_USER_PROFILE_PICTURE

export const UPLOAD_USER_PROFILE_PICTURE_REQUEST =
  "UPLOAD_USER_PROFILE_PICTURE_REQUEST";
export const UPLOAD_USER_PROFILE_PICTURE_SUCCESS =
  "UPLOAD_USER_PROFILE_PICTURE_SUCCESS";
export const UPLOAD_USER_PROFILE_PICTURE_RESET =
  "UPLOAD_USER_PROFILE_PICTURE_RESET";
export const UPLOAD_USER_PROFILE_PICTURE_FAILURE =
  "UPLOAD_USER_PROFILE_PICTURE_FAILURE";

export const CHANGE_BLOGS_ARTICLE = "CHANGE_BLOGS_ARTICLE";
