export const countryListAlpha3 = [
	{ AFG: 'Afghanistan', label: 'Afghanistan' },
	{ ALB: 'Albania', label: 'Albania' },
	{ DZA: 'Algeria', label: 'Algeria' },
	{ ASM: 'American Samoa', label: 'American Samoa' },
	{ AND: 'Andorra', label: 'Andorra' },
	{ AGO: 'Angola', label: 'Angola' },
	{ AIA: 'Anguilla', label: 'Anguilla' },
	{ ATA: 'Antarctica', label: 'Antarctica' },
	{ ATG: 'Antigua and Barbuda', label: 'Antigua and Barbuda' },
	{ ARG: 'Argentina', label: 'Argentina' },
	{ ARM: 'Armenia', label: 'Armenia' },
	{ ABW: 'Aruba', label: 'Aruba' },
	{ AUS: 'Australia', label: 'Australia' },
	{ AUT: 'Austria', label: 'Austria' },
	{ AZE: 'Azerbaijan', label: 'Azerbaijan' },
	{ BHS: 'Bahamas (the)', label: 'Bahamas (the)' },
	{ BHR: 'Bahrain', label: 'Bahrain' },
	{ BGD: 'Bangladesh', label: 'Bangladesh' },
	{ BRB: 'Barbados', label: 'Barbados' },
	{ BLR: 'Belarus', label: 'Belarus' },
	{ BEL: 'Belgium', label: 'Belgium' },
	{ BLZ: 'Belize', label: 'Belize' },
	{ BEN: 'Benin', label: 'Benin' },
	{ BMU: 'Bermuda', label: 'Bermuda' },
	{ BTN: 'Bhutan', label: 'Bhutan' },
	{ BOL: 'Bolivia (Plurinational State of)', label: 'Bolivia (Plurinational State of)' },
	{ BES: 'Bonaire Sint Eustatius and Saba', label: 'Bonaire Sint Eustatius and Saba' },
	{ BIH: 'Bosnia and Herzegovina', label: 'Bosnia and Herzegovina' },
	{ BWA: 'Botswana', label: 'Botswana' },
	{ BVT: 'Bouvet Island', label: 'Bouvet Island' },
	{ BRA: 'Brazil', label: 'Brazil' },
	{ IOT: 'British Indian Ocean Territory (the)', label: 'British Indian Ocean Territory (the)' },
	{ BRN: 'Brunei Darussalam', label: 'Brunei Darussalam' },
	{ BGR: 'Bulgaria', label: 'Bulgaria' },
	{ BFA: 'Burkina Faso', label: 'Burkina Faso' },
	{ BDI: 'Burundi', label: 'Burundi' },
	{ CPV: 'Cabo Verde', label: 'Cabo Verde' },
	{ KHM: 'Cambodia', label: 'Cambodia' },
	{ CMR: 'Cameroon', label: 'Cameroon' },
	{ CAN: 'Canada', label: 'Canada' },
	{ CYM: 'Cayman Islands (the)', label: 'Cayman Islands (the)' },
	{ CAF: 'Central African Republic (the)', label: 'Central African Republic (the)' },
	{ TCD: 'Chad', label: 'Chad' },
	{ CHL: 'Chile', label: 'Chile' },
	{ CHN: 'China', label: 'China' },
	{ CXR: 'Christmas Island', label: 'Christmas Island' },
	{ CCK: 'Cocos (Keeling) Islands (the)', label: 'Cocos (Keeling) Islands (the)' },
	{ COL: 'Colombia', label: 'Colombia' },
	{ COM: 'Comoros (the)', label: 'Comoros (the)' },
	{ COD: 'Congo (the Democratic Republic of the)', label: 'Congo (the Democratic Republic of the)' },
	{ COG: 'Congo (the)', label: 'Congo (the)' },
	{ COK: 'Cook Islands (the)', label: 'Cook Islands (the)' },
	{ CRI: 'Costa Rica', label: 'Costa Rica' },
	{ HRV: 'Croatia', label: 'Croatia' },
	{ CUB: 'Cuba', label: 'Cuba' },
	{ CUW: 'Curaçao', label: 'Curaçao' },
	{ CYP: 'Cyprus', label: 'Cyprus' },
	{ CZE: 'Czechia', label: 'Czechia' },
	{ CIV: 'Côte d Ivoire', label: 'Côte dIvoire' },
	{ DNK: 'Denmark', label: 'Denmark' },
	{ DJI: 'Djibouti', label: 'Djibouti' },
	{ DMA: 'Dominica', label: 'Dominica' },
	{ DOM: 'Dominican Republic (the)', label: 'Dominican Republic (the)' },
	{ ECU: 'Ecuador', label: 'Ecuador' },
	{ EGY: 'Egypt', label: 'Egypt' },
	{ SLV: 'El Salvador', label: 'El Salvador' },
	{ GNQ: 'Equatorial Guinea', label: 'Equatorial Guinea' },
	{ ERI: 'Eritrea', label: 'Eritrea' },
	{ EST: 'Estonia', label: 'Estonia' },
	{ SWZ: 'Eswatini', label: 'Eswatini' },
	{ ETH: 'Ethiopia', label: 'Ethiopia' },
	{ FLK: 'Falkland Islands (the) [Malvinas]', label: 'Falkland Islands (the) [Malvinas]' },
	{ FRO: 'Faroe Islands (the)', label: 'Faroe Islands (the)' },
	{ FJI: 'Fiji', label: 'Fiji' },
	{ FIN: 'Finland', label: 'Finland' },
	{ FRA: 'France', label: 'France' },
	{ GUF: 'French Guiana', label: 'French Guiana' },
	{ PYF: 'French Polynesia', label: 'French Polynesia' },
	{ ATF: 'French Southern Territories (the)', label: 'French Southern Territories (the)' },
	{ GAB: 'Gabon', label: 'Gabon' },
	{ GMB: 'Gambia (the)', label: 'Gambia (the)' },
	{ GEO: 'Georgia', label: 'Georgia' },
	{ DEU: 'Germany', label: 'Germany' },
	{ GHA: 'Ghana', label: 'Ghana' },
	{ GIB: 'Gibraltar', label: 'Gibraltar' },
	{ GRC: 'Greece', label: 'Greece' },
	{ GRL: 'Greenland', label: 'Greenland' },
	{ GRD: 'Grenada', label: 'Grenada' },
	{ GLP: 'Guadeloupe', label: 'Guadeloupe' },
	{ GUM: 'Guam', label: 'Guam' },
	{ GTM: 'Guatemala', label: 'Guatemala' },
	{ GGY: 'Guernsey', label: 'Guernsey' },
	{ GIN: 'Guinea', label: 'Guinea' },
	{ GNB: 'Guinea-Bissau', label: 'Guinea-Bissau' },
	{ GUY: 'Guyana', label: 'Guyana' },
	{ HTI: 'Haiti', label: 'Haiti' },
	{ HMD: 'Heard Island and McDonald Islands', label: 'Heard Island and McDonald Islands' },
	{ VAT: 'Holy See (the)', label: 'Holy See (the)' },
	{ HND: 'Honduras', label: 'Honduras' },
	{ HKG: 'Hong Kong', label: 'Hong Kong' },
	{ HUN: 'Hungary', label: 'Hungary' },
	{ ISL: 'Iceland', label: 'Iceland' },
	{ IND: 'India', label: 'India' },
	{ IDN: 'Indonesia', label: 'Indonesia' },
	{ IRN: 'Iran (Islamic Republic of)', label: 'Iran (Islamic Republic of)' },
	{ IRQ: 'Iraq', label: 'Iraq' },
	{ IRL: 'Ireland', label: 'Ireland' },
	{ IMN: 'Isle of Man', label: 'Isle of Man' },
	{ ISR: 'Israel', label: 'Israel' },
	{ ITA: 'Italy', label: 'Italy' },
	{ JAM: 'Jamaica', label: 'Jamaica' },
	{ JPN: 'Japan', label: 'Japan' },
	{ JEY: 'Jersey', label: 'Jersey' },
	{ JOR: 'Jordan', label: 'Jordan' },
	{ KAZ: 'Kazakhstan', label: 'Kazakhstan' },
	{ KEN: 'Kenya', label: 'Kenya' },
	{ KIR: 'Kiribati', label: 'Kiribati' },
	{ PRK: 'Korea the Democratic People s Republic of', label: 'Korea the Democratic Peoples Republic of ' },
	{ KOR: 'Korea (the Republic of)', label: 'Korea (the Republic of)' },
	{ KWT: 'Kuwait', label: 'Kuwait' },
	{ KGZ: 'Kyrgyzstan', label: 'Kyrgyzstan' },
	{ LAO: "Lao People's Democratic Republic (the)", label: "Lao People's Democratic Republic (the)" },
	{ LVA: 'Latvia', label: 'Latvia' },
	{ LBN: 'Lebanon', label: 'Lebanon' },
	{ LSO: 'Lesotho', label: 'Lesotho' },
	{ LBR: 'Liberia', label: 'Liberia' },
	{ LBY: 'Libya', label: 'Libya' },
	{ LIE: 'Liechtenstein', label: 'Liechtenstein' },
	{ LTU: 'Lithuania', label: 'Lithuania' },
	{ LUX: 'Luxembourg', label: 'Luxembourg' },
	{ MAC: 'Macao', label: 'Macao' },
	{ MDG: 'Madagascar', label: 'Madagascar' },
	{ MWI: 'Malawi', label: 'Malawi' },
	{ MYS: 'Malaysia', label: 'Malaysia' },
	{ MDV: 'Maldives', label: 'Maldives' },
	{ MLI: 'Mali', label: 'Mali' },
	{ MLT: 'Malta', label: 'Malta' },
	{ MHL: 'Marshall Islands (the)', label: 'Marshall Islands (the)' },
	{ MTQ: 'Martinique', label: 'Martinique' },
	{ MRT: 'Mauritania', label: 'Mauritania' },
	{ MUS: 'Mauritius', label: 'Mauritius' },
	{ MYT: 'Mayotte', label: 'Mayotte' },
	{ MEX: 'Mexico', label: 'Mexico' },
	{ FSM: 'Micronesia (Federated States of)', label: 'Micronesia (Federated States of)' },
	{ MDA: 'Moldova (the Republic of)', label: 'Moldova (the Republic of)' },
	{ MCO: 'Monaco', label: 'Monaco' },
	{ MNG: 'Mongolia', label: 'Mongolia' },
	{ MNE: 'Montenegro', label: 'Montenegro' },
	{ MSR: 'Montserrat', label: 'Montserrat' },
	{ MAR: 'Morocco', label: 'Morocco' },
	{ MOZ: 'Mozambique', label: 'Mozambique' },
	{ MMR: 'Myanmar', label: 'Myanmar' },
	{ NAM: 'Namibia', label: 'Namibia' },
	{ NRU: 'Nauru', label: 'Nauru' },
	{ NPL: 'Nepal', label: 'Nepal' },
	{ NLD: 'Netherlands (the)', label: 'Netherlands (the)' },
	{ NCL: 'New Caledonia', label: 'New Caledonia' },
	{ NZL: 'New Zealand', label: 'New Zealand' },
	{ NIC: 'Nicaragua', label: 'Nicaragua' },
	{ NER: 'Niger (the)', label: 'Niger (the)' },
	{ NGA: 'Nigeria', label: 'Nigeria' },
	{ NIU: 'Niue', label: 'Niue' },
	{ NFK: 'Norfolk Island', label: 'Norfolk Island' },
	{ MNP: 'Northern Mariana Islands (the)', label: 'Northern Mariana Islands (the)' },
	{ NOR: 'Norway', label: 'Norway' },
	{ OMN: 'Oman', label: 'Oman' },
	{ PAK: 'Pakistan', label: 'Pakistan' },
	{ PLW: 'Palau', label: 'Palau' },
	{ PSE: 'Palestine State of', label: 'Palestine State of' },
	{ PAN: 'Panama', label: 'Panama' },
	{ PNG: 'Papua New Guinea', label: 'Papua New Guinea' },
	{ PRY: 'Paraguay', label: 'Paraguay' },
	{ PER: 'Peru', label: 'Peru' },
	{ PHL: 'Philippines (the)', label: 'Philippines (the)' },
	{ PCN: 'Pitcairn', label: 'Pitcairn' },
	{ POL: 'Poland', label: 'Poland' },
	{ PRT: 'Portugal', label: 'Portugal' },
	{ PRI: 'Puerto Rico', label: 'Puerto Rico' },
	{ QAT: 'Qatar', label: 'Qatar' },
	{ MKD: 'Republic of North Macedonia', label: 'Republic of North Macedonia' },
	{ ROU: 'Romania', label: 'Romania' },
	{ RUS: 'Russian Federation (the)', label: 'Russian Federation (the)' },
	{ RWA: 'Rwanda', label: 'Rwanda' },
	{ REU: 'Réunion', label: 'Réunion' },
	{ BLM: 'Saint Barthélemy', label: 'Saint Barthélemy' },
	{ SHN: 'Saint Helena Ascension and Tristan da Cunha', label: 'Saint Helena Ascension and Tristan da Cunha' },
	{ KNA: 'Saint Kitts and Nevis', label: 'Saint Kitts and Nevis' },
	{ LCA: 'Saint Lucia', label: 'Saint Lucia' },
	{ MAF: 'Saint Martin (French part)', label: 'Saint Martin (French part)' },
	{ SPM: 'Saint Pierre and Miquelon', label: 'Saint Pierre and Miquelon' },
	{ VCT: 'Saint Vincent and the Grenadines', label: 'Saint Vincent and the Grenadines' },
	{ WSM: 'Samoa', label: 'Samoa' },
	{ SMR: 'San Marino', label: 'San Marino' },
	{ STP: 'Sao Tome and Principe', label: 'Sao Tome and Principe' },
	{ SAU: 'Saudi Arabia', label: 'Saudi Arabia' },
	{ SEN: 'Senegal', label: 'Senegal' },
	{ SRB: 'Serbia', label: 'Serbia' },
	{ SYC: 'Seychelles', label: 'Seychelles' },
	{ SLE: 'Sierra Leone', label: 'Sierra Leone' },
	{ SGP: 'Singapore', label: 'Singapore' },
	{ SXM: 'Sint Maarten (Dutch part)', label: 'Sint Maarten (Dutch part)' },
	{ SVK: 'Slovakia', label: 'Slovakia' },
	{ SVN: 'Slovenia', label: 'Slovenia' },
	{ SLB: 'Solomon Islands', label: 'Solomon Islands' },
	{ SOM: 'Somalia', label: 'Somalia' },
	{ ZAF: 'South Africa', label: 'South Africa' },
	{ SGS: 'South Georgia and the South Sandwich Islands', label: 'South Georgia and the South Sandwich Islands' },
	{ SSD: 'South Sudan', label: 'South Sudan' },
	{ ESP: 'Spain', label: 'Spain' },
	{ LKA: 'Sri Lanka', label: 'Sri Lanka' },
	{ SDN: 'Sudan (the)', label: 'Sudan (the)' },
	{ SUR: 'Suriname', label: 'Suriname' },
	{ SJM: 'Svalbard and Jan Mayen', label: 'Svalbard and Jan Mayen' },
	{ SWE: 'Sweden', label: 'Sweden' },
	{ CHE: 'Switzerland', label: 'Switzerland' },
	{ SYR: 'Syrian Arab Republic', label: 'Syrian Arab Republic' },
	{ TWN: 'Taiwan', label: 'Taiwan' },
	{ TJK: 'Tajikistan', label: 'Tajikistan' },
	{ TZA: 'Tanzania United Republic of', label: 'Tanzania United Republic of' },
	{ THA: 'Thailand', label: 'Thailand' },
	{ TLS: 'Timor-Leste', label: 'Timor-Leste' },
	{ TGO: 'Togo', label: 'Togo' },
	{ TKL: 'Tokelau', label: 'Tokelau' },
	{ TON: 'Tonga', label: 'Tonga' },
	{ TTO: 'Trinidad and Tobago', label: 'Trinidad and Tobago' },
	{ TUN: 'Tunisia', label: 'Tunisia' },
	{ TUR: 'Turkey', label: 'Turkey' },
	{ TKM: 'Turkmenistan', label: 'Turkmenistan' },
	{ TCA: 'Turks and Caicos Islands (the)', label: 'Turks and Caicos Islands (the)' },
	{ TUV: 'Tuvalu', label: 'Tuvalu' },
	{ UGA: 'Uganda', label: 'Uganda' },
	{ UKR: 'Ukraine', label: 'Ukraine' },
	{ ARE: 'United Arab Emirates (the)', label: 'United Arab Emirates (the)' },
	{
		GBR: 'United Kingdom of Great Britain and Northern Ireland (the)',
		label: 'United Kingdom of Great Britain and Northern Ireland (the)'
	},
	{ UMI: 'United States Minor Outlying Islands (the)', label: 'United States Minor Outlying Islands (the)' },
	{ USA: 'United States of America (the)', label: 'United States of America (the)' },
	{ URY: 'Uruguay', label: 'Uruguay' },
	{ UZB: 'Uzbekistan', label: 'Uzbekistan' },
	{ VUT: 'Vanuatu', label: 'Vanuatu' },
	{ VEN: 'Venezuela (Bolivarian Republic of)', label: 'Venezuela (Bolivarian Republic of)' },
	{ VNM: 'Viet Nam', label: 'Viet Nam' },
	{ VGB: 'Virgin Islands (British)', label: 'Virgin Islands (British)' },
	{ VIR: 'Virgin Islands (U.S.)', label: 'Virgin Islands (U.S.)' },
	{ WLF: 'Wallis and Futuna', label: 'Wallis and Futuna' },
	{ ESH: 'Western Sahara', label: 'Western Sahara' },
	{ YEM: 'Yemen', label: 'Yemen' },
	{ ZMB: 'Zambia', label: 'Zambia' },
	{ ZWE: 'Zimbabwe', label: 'Zimbabwe' },
	{ ALA: 'Åland Islands', label: 'Åland Islands' }
];
